### ISSUE TITLE
The user gets a operation cannot be performed error when saving a document

### ISSUE THREAD

**Issue by MikeWilliams-UK** [Chem4Word/Version3-1#42]
**Describe the bug**
The user gets an error message when saving a document

**To Reproduce**
Steps to reproduce the behaviour:
Unknown at this time

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro for Workstations
 - Word Version O365 Professional Plus 64 bit

Stack Trace ...
```
Exception in OnDocumentBeforeSave()
System.Runtime.InteropServices.COMException (0xE0041804):
The operation cannot be performed on a stream that is about to be deleted.
   at Microsoft.Office.Core._CustomXMLPart.Delete()
   at Chem4Word.Helpers.CustomXmlPartHelper.RemoveOrphanedXmlParts(Document doc) in C:\Dev\vsts\Chem4Word\Version3-1\src\Chem4Word.V3\Helpers\CustomXMLPartHelper.cs:line 128
   at Chem4Word.Chem4WordV3.OnDocumentBeforeSave(Document doc, Boolean& saveAsUi, Boolean& cancel) in C:\Dev\vsts\Chem4Word\Version3-1\src\Chem4Word.V3\Chem4WordV3.cs:line 1784
```

**Comment by MikeWilliams-UK** [comment]
Fixed by beta-6
