### ISSUE TITLE
Error when inserting chemistry from the navigator

### ISSUE THREAD

**Issue by MikeWilliams-UK** [Chem4Word/Version3-1#43]
**Describe the bug**
The user gets an error message when inserting chemistry from the navigator

**To Reproduce**
Steps to reproduce the behaviour:
Unknown, but telemetry shows that Copy button pressed twice.
As far as I can tell the double click protection of the buttons is working.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro for Workstations
 - Word Version O365 Professional Plus 64 bit

```
Exception in TaskPaneHelper.InsertChemistry()
System.Exception: Error in Insert2DChemistry; See InnerException for details --->
System.Runtime.InteropServices.SEHException: External component has thrown an exception.
   at Microsoft.Office.Core.CustomXMLPartsClass.Add(String XML, Object SchemaCollection)
   at Chem4Word.Helpers.ChemistryHelper.Insert2DChemistry(Document doc, String cml, Boolean isCopy) in C:\Dev\vsts\Chem4Word\Version3-1\src\Chem4Word.V3\Helpers\ChemistryHelper.cs:line 90
   --- End of inner exception stack trace ---
   at Chem4Word.Helpers.ChemistryHelper.Insert2DChemistry(Document doc, String cml, Boolean isCopy) in C:\Dev\vsts\Chem4Word\Version3-1\src\Chem4Word.V3\Helpers\ChemistryHelper.cs:line 109
   at Chem4Word.Helpers.TaskPaneHelper.InsertChemistry(Boolean isCopy, Application app, Display display, Boolean fromLibrary) in C:\Dev\vsts\Chem4Word\Version3-1\src\Chem4Word.V3\Helpers\TaskPaneHelper.cs:line 80
```

**Comment by tomyan112** [comment]
Sorry, it happens in random so I can't reproduce the problem too.

**Comment by MikeWilliams-UK** [comment]
Thanks for taking the time to reply.

**Comment by MikeWilliams-UK** [comment]
Closed as unable to reproduce.
